name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > keyfile
        chmod 600 keyfile
        ssh -o StrictHostKeyChecking=no -i keyfile ubuntu@ec2-35-170-242-10.compute-1.amazonaws.com "sudo bash ~/deploy.sh"
