name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted 

    strategy: 
      matrix:
        node-version: [20.16.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create PEM file
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > ~/actions-runner/_work/week-9/week-9/server/private-key.pem
        chmod 600 ~/actions-runner/_work/week-9/week-9/server/private-key.pem  # Set secure permissions

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ~/actions-runner/_work/week-9/week-9/server

    - name: Restart Application
      run: pm2 restart index
