name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted 

    strategy: 
      matrix:
        node-version: [20.16.0]

    steps:
    - name: Connect to the server and pull latest changes
      run: |
        cd ~/actions-runner/_work/week-9/week-9  # Change to your project directory
        git pull origin master  # Pull latest changes from master branch

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ~/actions-runner/_work/week-9/week-9/server  # Change directory automatically

    - name: Restart Application
      run: pm2 restart index

