name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create SSH Key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > sampleAppKey-1.pem
        chmod 600 sampleAppKey-1.pem

    - name: Add EC2 to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-3-84-55-152.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH into EC2 and Deploy
      run: |
        ssh -i sampleAppKey-1.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-84-55-152.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/actions-runner/_work/week-9/week-9
          git pull origin master
          cd server
          npm install
          pm2 restart index
        EOF
